version: "3"
services:

  repo:
    container_name: repo
    build: .
    restart: always
    networks:
      - repo-net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - repo-net
    links:
      - repo

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - repo-net
    volumes:
      - ./db:/data/db

networks:
  repo-net:
    driver: bridge
